server:
  port: 8909
security:
  basic:
    enabled: false
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# H2 during development
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: user-service
  #datasource:
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    #url: jdbc:oracle:thin:@localhost:1521:xe
    #username: HydraTrainee
    #password: momonga
  jpa:
    #database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
  #rabbitmq:
    #host: 35.183.27.227
    #port: 5672
    #username: guest
    #password: guest
 