#Server Configuration
server:
  port: 10001
security:
  basic:
    enabled: false

# H2 during development
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: user-service
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: GAMBIT
#    password: p4ssw0rd
  jpa:
#    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
#  kafka:
#    consumer:
#      auto-offset-reset: earliest
#      group-id: gambit
#    bootstrap-servers: ${KAFKA_URL}
#    topic:
#      trainer.register: trainer.register.t
#      trainer.update: trainer.update.t
#      trainer.delete: trainer.delete.t
#      trainee.register: trainee.register.t
#      trainee.update: trainee.update.t
#      trainee.delete: trainee.delete.t

#Eureka Client Configuration
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOME}
